cmake_minimum_required(VERSION 3.16)

project(sdg-control VERSION 0.8 LANGUAGES CXX C)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

include ( CMakePackageConfigHelpers )
include ( GNUInstallDirs )
include ( CheckIncludeFile )
include ( CheckFunctionExists )
include ( CheckCSourceCompiles )
find_package ( PkgConfig )

string(TIMESTAMP BUILD_TIME "%Y%m%d %H:%M:%S")

option(SDG_DEBUG "Enable SDG SCPI debug output" OFF)
option(SDG_DEVELOPER_UI "Extra GUI fields to aid development" OFF)
option(SDG_BUILD_TEST "Build sdg_test CLI in test_instrument directory" OFF)

if (SDG_DEBUG)
    MESSAGE( STATUS ">> SDG_DEBUG set, messages sent to console" )
endif ()
if (SDG_DEVELOPER_UI)
    MESSAGE( STATUS ">> SDG_DEVELOPER_UI set, extra fields to aid development" )
endif ()

set(OS_LINUX 0)
set(CONTAINS_LINUX 0)
set(OS_ANDROID 0)
set(OS_FREEBSD 0)
set(CONTAINS_BSD 0)
set(OS_NETBSD 0)
set(OS_OPENBSD 0)
set(OS_SOLARIS 0)
set(OS_AIX 0)
set(OS_HAIKU 0)
set(OS_WIN32 0)
set(CONTAINS_WIN32 0)
set(ENV_MINGW 0)
set(ENV_CYGWIN 0)
set(OS_MACOS 0)

message(STATUS ">> cmake System Name: ${CMAKE_SYSTEM_NAME}")
if (CYGWIN)
    message(STATUS ">> Cygwin on Win32")
    set(ENV_CYGWIN 1)
    set(CONTAINS_WIN32 1)
elseif (MINGW)
    message(STATUS ">> MinGW on Win32")
    set(ENV_MINGW 1)
    set(CONTAINS_WIN32 1)
    check_function_exists(setmode HAVE_SETMODE)
    check_function_exists(_setmode HAVE__SETMODE)
elseif (WIN32)
    message(STATUS ">> Windows platform")
    set(OS_WIN32 1)
    set(CONTAINS_WIN32 1)
    if (MSVC)
        message(STATUS ">> MSVC compiler detected (Visual Studio)")
    endif ()
elseif (ANDROID)
    message(STATUS ">> Android platform")
    set(OS_ANDROID 1)
    set(CONTAINS_LINUX 1)
elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(STATUS ">> Linux platform")
    set(OS_LINUX 1)
    set(CONTAINS_LINUX 1)
elseif (CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
    message(STATUS ">> FreeBSD platform")
    set(OS_FREEBSD 1)
    set(CONTAINS_BSD 1)
elseif (CMAKE_SYSTEM_NAME STREQUAL "NetBSD")
    message(STATUS ">> NetBSD platform")
    set(OS_NETBSD 1)
    set(CONTAINS_BSD 1)
elseif (CMAKE_SYSTEM_NAME STREQUAL "OpenBSD")
    message(STATUS ">> OpenBSD platform")
    set(OS_OPENBSD 1)
    set(CONTAINS_BSD 1)
elseif (CMAKE_SYSTEM_NAME STREQUAL "SunOS")
    message(STATUS ">> Solaris platform")
    set(OS_SOLARIS 1)
elseif (CMAKE_SYSTEM_NAME STREQUAL "AIX")
    message(STATUS ">> AIX platform")
    set(OS_AIX 1)
elseif (CMAKE_SYSTEM_NAME STREQUAL "HAIKU")
    message(STATUS ">> HAIKU platform")
    set(OS_HAIKU 1)
elseif (APPLE)
    message(STATUS ">> Apple (macOS) platform")
    set(OS_MACOS 1)
else()
    message(STATUS "Unknown platform: ${CMAKE_SYSTEM_NAME}")
endif()

if ( NEED_GETOPT_LONG OR NEED_GETOPT_H )
    MESSAGE( STATUS ">> Couldn't find getopt/getopt_long, use local version" )
    set (getopt_if_needed ${CMAKE_SOURCE_DIR}/common/getopt_long.c)
else ( )
    set (getopt_if_needed "")
endif ( )

CHECK_INCLUDE_FILE( "getopt.h" HAVE_GETOPT_H )    # non-standard but common
check_function_exists(getopt_long HAVE_GETOPT_LONG)

set(NEED_GETOPT_H 1)
if ( HAVE_GETOPT_H )
    set(NEED_GETOPT_H 0)
endif ( HAVE_GETOPT_H )

set(NEED_GETOPT_LONG 1)
if ( HAVE_GETOPT_LONG )
    set(NEED_GETOPT_LONG 0)
endif ( HAVE_GETOPT_LONG )

set(COMP_GCC 0)
set(COMP_CLANG 0)
set(COMP_MSVC 0)
set(COMP_UNKNOWN 0)

message(STATUS "CMAKE_C_COMPILER     = ${CMAKE_C_COMPILER}")
message(STATUS "CMAKE_C_COMPILER_ID  = ${CMAKE_C_COMPILER_ID}")
message(STATUS "CMAKE_C_COMPILER_VERSION = ${CMAKE_C_COMPILER_VERSION}")

# How to read environment variable CC ?  CC here is '-DCC=/usr/bin/clang'

if ( $ENV{CC} MATCHES "gcc" )
    MESSAGE( STATUS ">> GCC compiler selected [ev]" )
    set(COMP_GCC 1)
elseif ( $ENV{CC} MATCHES "clang" )
    MESSAGE( STATUS ">> CLANG compiler selected [ev]" )
    set(COMP_CLANG 1)
elseif ( CMAKE_C_COMPILER_ID MATCHES "GNU" )
    MESSAGE( STATUS ">> GCC compiler detected" )
    set(COMP_GCC 1)
elseif (CMAKE_C_COMPILER_ID MATCHES "Clang")
    MESSAGE( STATUS ">> CLANG compiler detected" )
    set(COMP_CLANG 1)
elseif ( MSVC )
    MESSAGE( STATUS ">> MSVC compiler detected" )
    set(COMP_MSVC 1)
else ()
    MESSAGE( STATUS ">> did NOT detect compiler" )
    set(COMP_UNKNOWN 1)
endif ()

function ( set_compile_options util_name )
    if ( SDG_DEBUG )
        target_compile_definitions(${util_name} PRIVATE DEBUG)
        if ( COMP_GCC )
            target_compile_options(${util_name} PRIVATE
                -Wextra -Wmisleading-indentation -Wduplicated-cond -Wlogical-op
                -Wnull-dereference -Wshadow -Wunused -Wsizeof-array-argument
                -Wduplicated-branches -Wparentheses)
        elseif ( COMP_CLANG )
            target_compile_options(${util_name} PRIVATE
                -Wextra -Wshadow
                -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wundef
                -Wimplicit-fallthrough -Woverloaded-virtual -Wnon-virtual-dtor
                -Wcast-align -Wcast-qual -Wunused
                -Wunreachable-code)
                # -Wpedantic -Wconversion -Wsign-conversion -Wold-style-cast
                # -Weverything # generates way too much nitpicking
        elseif ( COMP_MSVC )
            # MESSAGE( STATUS ">> MSVC compiler detected" )
        else ()
            # MESSAGE( STATUS ">> did NOT detect compiler" )
        endif ()
    endif ( SDG_DEBUG )
endfunction ( set_compile_options )

configure_file( ${CMAKE_SOURCE_DIR}/config.h.in.cmake ${CMAKE_BINARY_DIR}/config.h )


if (MSVC)
    add_compile_definitions ( HAVE_CONFIG_H )
else ()
    add_compile_definitions ( _LARGEFILE64_SOURCE _FILE_OFFSET_BITS=64 HAVE_CONFIG_H )
endif ()

find_package(Qt6 REQUIRED COMPONENTS Core Network Widgets)

set(CMAKE_AUTOMOC ON)

add_subdirectory(instrument)
if (SDG_BUILD_TEST)
    add_subdirectory(test_instrument)
endif ()
add_subdirectory(app)


set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VENDOR "Douglas Gilbert")
set(CPACK_PACKAGE_CONTACT "dgilbert@interlog.com")
set(CPACK_PROJECT_VERSION "${PROJECT_VERSION}")

SET(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Siglent SDG2000X function generator controller, QT based using SCPI over TCP")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Douglas Gilbert")
SET(CPACK_DEBIAN_PACKAGE_SECTION "admin")

SET(CPACK_RPM_PACKAGE_DESCRIPTION "Siglent SDG2000X function generator controller, QT based using SCPI over TCP")
SET(CPACK_RPM_PACKAGE_LICENSE "BSD-2-clause")
SET(CPACK_RPM_PACKAGE_VENDOR "Douglas Gilbert")

if (CONTAINS_LINUX)
    set(CPACK_GENERATOR "")
    find_program(DPKG_EXECUTABLE dpkg)
    if (DPKG_EXECUTABLE)
        list(APPEND CPACK_GENERATOR "DEB")
    endif ()
    find_program(RPMBUILD_EXECUTABLE rpmbuild)
    if (RPMBUILD_EXECUTABLE)
        list(APPEND CPACK_GENERATOR "RPM")
    endif ()
elseif (OS_FREEBSD)
    SET(CPACK_GENERATOR "FREEBSD")
else ()
    MESSAGE(STATUS "<<>> No cpack generator available")
endif (CONTAINS_LINUX)

include(CPack)
include(CTest)
