cmake_minimum_required(VERSION 3.16)

project(sdg-control VERSION 0.7 LANGUAGES CXX C)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

include ( CMakePackageConfigHelpers )
include ( GNUInstallDirs )
include ( CheckIncludeFile )
include ( CheckFunctionExists )
include ( CheckCSourceCompiles )
find_package ( PkgConfig )

string(TIMESTAMP BUILD_TIME "%Y%m%d %H:%M:%S")

option(SDG_DEBUG "Enable SDG SCPI debug output" OFF)
option(SDG_DEVELOPER_UI "Extra fields to aid development" OFF)

if (SDG_DEBUG)
    MESSAGE( STATUS ">> SDG_DEBUG set, messages to console" )
endif ()
if (SDG_DEVELOPER_UI)
    MESSAGE( STATUS ">> SDG_DEVELOPER_UI set, extra fields to aid development" )
endif ()

set(OS_LINUX 0)
set(CONTAINS_LINUX 0)
set(OS_ANDROID 0)
set(OS_FREEBSD 0)
set(CONTAINS_BSD 0)
set(OS_NETBSD 0)
set(OS_OPENBSD 0)
set(OS_SOLARIS 0)
set(OS_AIX 0)
set(OS_HAIKU 0)
set(OS_WIN32 0)
set(CONTAINS_WIN32 0)
set(ENV_MINGW 0)
set(ENV_CYGWIN 0)
set(OS_MACOS 0)

message(STATUS ">> cmake System Name: ${CMAKE_SYSTEM_NAME}")
if (CYGWIN)
    message(STATUS ">> Cygwin build")
    set(ENV_CYGWIN 1)
    set(CONTAINS_WIN32 1)
elseif (MINGW)
    message(STATUS ">> MinGW build")
    set(ENV_MINGW 1)
    set(CONTAINS_WIN32 1)
    check_function_exists(setmode HAVE_SETMODE)
    check_function_exists(_setmode HAVE__SETMODE)
elseif (WIN32)
    message(STATUS ">> Windows build")
    set(OS_WIN32 1)
    set(CONTAINS_WIN32 1)
elseif (ANDROID)
    message(STATUS ">> Android build")
    set(OS_ANDROID 1)
    set(CONTAINS_LINUX 1)
elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(STATUS ">> Linux build")
    set(OS_LINUX 1)
    set(CONTAINS_LINUX 1)
elseif (CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
    message(STATUS ">> FreeBSD build")
    set(OS_FREEBSD 1)
    set(CONTAINS_BSD 1)
elseif (CMAKE_SYSTEM_NAME STREQUAL "NetBSD")
    message(STATUS ">> NetBSD build")
    set(OS_NETBSD 1)
    set(CONTAINS_BSD 1)
elseif (CMAKE_SYSTEM_NAME STREQUAL "OpenBSD")
    message(STATUS ">> OpenBSD build")
    set(OS_OPENBSD 1)
    set(CONTAINS_BSD 1)
elseif (CMAKE_SYSTEM_NAME STREQUAL "SunOS")
    message(STATUS ">> Solaris build")
    set(OS_SOLARIS 1)
elseif (CMAKE_SYSTEM_NAME STREQUAL "AIX")
    message(STATUS ">> AIX build")
    set(OS_AIX 1)
elseif (CMAKE_SYSTEM_NAME STREQUAL "HAIKU")
    message(STATUS ">> HAIKU build")
    set(OS_HAIKU 1)
elseif (APPLE)
    message(STATUS ">> Apply (macOS) build")
    set(OS_MACOS 1)
else()
    message(STATUS "Unknown system: ${CMAKE_SYSTEM_NAME}")
endif()

CHECK_INCLUDE_FILE( "getopt.h" HAVE_GETOPT_H )    # non-standard but common
check_function_exists(getopt_long HAVE_GETOPT_LONG)

configure_file( ${CMAKE_SOURCE_DIR}/config.h.in.cmake ${CMAKE_BINARY_DIR}/config.h )


if (MSVC)
    add_compile_definitions ( HAVE_CONFIG_H )
    add_compile_options(/Zc:__cplusplus)
    add_compile_options(/permissive-)
else ()
    add_compile_definitions ( _LARGEFILE64_SOURCE _FILE_OFFSET_BITS=64 HAVE_CONFIG_H )
endif ()

find_package(Qt6 REQUIRED COMPONENTS Core Network Widgets)

set(CMAKE_AUTOMOC ON)

add_subdirectory(instrument)
# Speed up build by leaving out test_scpi
add_subdirectory(test_scpi)
add_subdirectory(app)


set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VENDOR "Douglas Gilbert")
set(CPACK_PACKAGE_CONTACT "dgilbert@interlog.com")
set(CPACK_PROJECT_VERSION "${PROJECT_VERSION}")

SET(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Siglent SDG2000X function generator controller, QT based using SCPI over TCP")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Douglas Gilbert")
SET(CPACK_DEBIAN_PACKAGE_SECTION "admin")

SET(CPACK_RPM_PACKAGE_DESCRIPTION "Siglent SDG2000X function generator controller, QT based using SCPI over TCP")
SET(CPACK_RPM_PACKAGE_LICENSE "BSD-2-clause")
SET(CPACK_RPM_PACKAGE_VENDOR "Douglas Gilbert")

if ( CONTAINS_LINUX )
    set(CPACK_GENERATOR "")
    find_program(DPKG_EXECUTABLE dpkg)
    if (DPKG_EXECUTABLE)
        list(APPEND CPACK_GENERATOR "DEB")
    endif ()
    find_program(RPMBUILD_EXECUTABLE rpmbuild)
    if (RPMBUILD_EXECUTABLE)
        list(APPEND CPACK_GENERATOR "RPM")
    endif ()
elseif ( OS_FREEBSD )
    SET(CPACK_GENERATOR "FREEBSD")
else ()
    MESSAGE(STATUS "<<>> No cpack generator available")
endif ( CONTAINS_LINUX )

include(CPack)
include(CTest)
